# Generated by Django 2.2.10 on 2020-02-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_auto_20200221_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='published_date',
        ),
    ]
