# Generated by Django 2.2.10 on 2020-02-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_auto_20200223_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='名前')),
                ('pasword', models.CharField(max_length=20, verbose_name='パスワード')),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
