# Generated by Django 2.2.10 on 2020-02-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_auto_20200226_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repasword',
            field=models.CharField(default='確認パスワード', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='pasword',
            field=models.CharField(default='パスワード', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='名前', max_length=20),
        ),
    ]
