# Generated by Django 2.2.10 on 2020-03-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0007_auto_20200309_0547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCreate',
        ),
    ]
