# Generated by Django 2.2.10 on 2020-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0009_auto_20200309_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='usercreate',
            name='password',
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
